name: Selenium tests

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-6.0
    
    - name: Build and test
      run: |
        dotnet restore
        dotnet build
        dotnet test --filter "FullyQualifiedName=WRMAutotests.Tests.WebUI.EndToEndTests.E2E001.E2E001_Test" 
        
  
