name: Selenium tests

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-6.0

    - name: Install Allure
      run: |
        sudo apt-add-repository -y ppa:yandex-qatools/allure
        sudo apt-get update
        sudo apt-get install -y allure
      
    - name: Build and test
      run: |
        dotnet restore
        dotnet build
        dotnet test --filter "FullyQualifiedName=WRMAutotests.Tests.WebUI.EndToEndTests.E2E001.E2E001_Test" 
        
    - name: Generate Allure report
      run: allure generate -c build/allure-results -o allure-report
        
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Test local action
      uses: ./allure-report-action
      if: always()
      id: allure-report
      with:
        allure_results: build/allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
