name: Selenium tests

on: 
  workflow_dispatch:
    inputs:
        username:
          description: Username
          default: "bob"
          required: true
        password:
          description: Password (For example only. It's not secure.)
          default: "bob"
          required: true

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      run: |
        choco install dotnet-sdk -y

    - name: Build and test
      run: |
        dotnet restore
        dotnet build
        dotnet test --filter "FullyQualifiedName=WRMAutotests.Tests.WebUI.EndToEndTests.E2E001.E2E001_Test"
